services:
  sentiment-analyzer-bert:
    container_name: sentiment-analyzer-bert
    build:
      context: ./bert
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    restart: unless-stopped
    environment:
      CUDA_VISIBLE_DEVICES: 0
    gpus: all


  sentiment-analyzer-tts:
    container_name: sentiment-analyzer-tts
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "8013:8000"
    restart: unless-stopped
    environment:
      CUDA_VISIBLE_DEVICES: 0
    gpus: all


  sentiment-analyzer-backend:
    container_name: sentiment-analyzer-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8012:8000"
    volumes:
      - llm_cache:/root/.cache
    depends_on:
      - sentiment-analyzer-bert
    restart: unless-stopped

volumes:
  ollama_models:
    driver: local
  llm_cache:
    driver: local