services:
  frontend:
    container_name: content-analysis-frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - TEXT_ANALYZE_API_URL=http://192.168.72.6:8012/text_analyze
      - URL_ANALYZE_API_URL=http://192.168.72.6:8012/url_analyze
    restart: unless-stopped   # ← add this line
